### ISSUE TITLE
Package 'python-setuptools' conflicts with another package

### ISSUE THREAD

**Issue by alaughlin** [kisslinux/repo#88] opened 2019-08-31 13:47 UTC
I'm attempting to install `xorg-server` and `python-setuptools` fails installation with the above error. Is there a way to determine what the conflict is and how to resolve it?

**Comment by dylanaraps** [comment] 2019-08-31 13:55
Is there no other output from the package manager?

**Comment by alaughlin** [comment] 2019-08-31 14:18
Here's the output:

```
[1;32m=>[m [python-setuptools] Checking for package conflicts.
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/windows_support.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/wheel.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/version.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/unicode_utils.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/ssl_support.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/site-patch.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/script.tmpl
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/script (dev).tmpl
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/sandbox.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/py33compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/py31compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/py27compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/pep425tags.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/package_index.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/namespaces.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/msvc.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/monkey.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/lib2to3_ex.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/launch.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/glob.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/glibc.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/extern/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/extern/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/extension.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/dist.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/depends.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/dep_util.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/config.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/upload_docs.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/upload.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/test.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/setopt.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/sdist.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/saveopts.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/rotate.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/register.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/py36compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/install_scripts.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/install_lib.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/install_egg_info.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/install.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/egg_info.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/dist_info.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/develop.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/build_py.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/build_ext.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/build_clib.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/bdist_wininst.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/bdist_rpm.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/alias.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/upload_docs.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/upload.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/test.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/setopt.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/sdist.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/saveopts.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/rotate.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/register.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/py36compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/install_scripts.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/install_lib.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/install_egg_info.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/install.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/egg_info.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/easy_install.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/dist_info.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/develop.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/build_py.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/build_ext.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/build_clib.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/bdist_wininst.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/bdist_rpm.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/bdist_egg.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/alias.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/command/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/build_meta.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/archive_util.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/six.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/pyparsing.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/version.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/utils.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/requirements.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/markers.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/_structures.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/_compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/version.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/utils.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/specifiers.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/requirements.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/markers.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/_structures.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/_compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__pycache__/__about__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/packaging/__about__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/__pycache__/six.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/__pycache__/pyparsing.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_vendor/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/_deprecation_warning.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/windows_support.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/wheel.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/version.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/unicode_utils.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/ssl_support.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/site-patch.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/sandbox.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/py33compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/py31compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/py27compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/pep425tags.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/package_index.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/namespaces.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/msvc.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/monkey.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/lib2to3_ex.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/launch.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/glob.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/glibc.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/extension.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/dist.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/depends.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/dep_util.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/config.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/build_meta.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/archive_util.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/_deprecation_warning.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/setuptools/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/py31compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/extern/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/extern/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/six.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/utils.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/markers.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_structures.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_compat.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/version.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/utils.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/specifiers.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/requirements.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/markers.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/_structures.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/_compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__pycache__/__about__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/__about__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/appdirs.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/__pycache__/six.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/__pycache__/pyparsing.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/__pycache__/appdirs.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/_vendor/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/__pycache__/py31compat.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/__pycache__/__init__.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/pkg_resources/__init__.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/easy_install.py
/var/db/kiss/installed/python/manifest:/usr/lib/python3.7/site-packages/__pycache__/easy_install.cpython-37.pyc
/var/db/kiss/installed/python/manifest:/usr/bin/easy_install-3.7
[1;31m!>[m Package 'python-setuptools' conflicts with another package.
```

**Comment by dylanaraps** [comment] 2019-08-31 14:20
It looks like Python 3 may provide `python-setuptools`. I can't seem to reproduce this on my machine. What's the output of `kiss list python`?

**Comment by alaughlin** [comment] 2019-08-31 14:22
`python 3.7.4-3`

**Comment by dylanaraps** [comment] 2019-08-31 14:30
Run `kiss update` and then try and continue with your builds. The problem should be fixed. :+1:

**Comment by alaughlin** [comment] 2019-08-31 14:36
So I ran `kiss update` and then ran `kiss b Xorg-server` and got this now:

```
[1;32m=>[m Resolving dependencies.
[1;32m=>[m Building: meson glib xorgproto libXau xcb-proto xorg-util-macros libxcb xtrans libX11 libXfixes libXdamage libXext libXrender libXxf86vm libpciaccess libdrm libxshmfence libXrandr cmake llvm python-mako mesa pixman freetype-harfbuzz libfontenc libXfont2 libepoxy libxkbfile xinit xkbcomp xkeyboard-config xorg-server.
[1;32m=>[m Continue?: Press Enter to continue or Ctrl+C to abort here.
[1;32m=>[m Checking to see if any dependencies have already been built.
[1;32m=>[m Installing any pre-built dependencies.
[1;32m=>[m [meson] Checking repository files.
[1;32m=>[m [glib] Checking repository files.
[1;32m=>[m [xorgproto] Checking repository files.
[1;32m=>[m [libXau] Checking repository files.
[1;32m=>[m [xcb-proto] Checking repository files.
[1;32m=>[m [xorg-util-macros] Checking repository files.
[1;32m=>[m [libxcb] Checking repository files.
[1;32m=>[m [xtrans] Checking repository files.
[1;32m=>[m [libX11] Checking repository files.
[1;32m=>[m [libXfixes] Checking repository files.
[1;32m=>[m [libXdamage] Checking repository files.
[1;32m=>[m [libXext] Checking repository files.
[1;32m=>[m [libXrender] Checking repository files.
[1;32m=>[m [libXxf86vm] Checking repository files.
[1;32m=>[m [libpciaccess] Checking repository files.
[1;32m=>[m [libdrm] Checking repository files.
[1;32m=>[m [libxshmfence] Checking repository files.
[1;32m=>[m [libXrandr] Checking repository files.
[1;32m=>[m [cmake] Checking repository files.
[1;32m=>[m [llvm] Checking repository files.
[1;32m=>[m [python-mako] Checking repository files.
[1;32m=>[m [mesa] Checking repository files.
[1;32m=>[m [pixman] Checking repository files.
[1;32m=>[m [freetype-harfbuzz] Checking repository files.
[1;32m=>[m [libfontenc] Checking repository files.
[1;32m=>[m [libXfont2] Checking repository files.
[1;32m=>[m [libepoxy] Checking repository files.
[1;32m=>[m [libxkbfile] Checking repository files.
[1;32m=>[m [xinit] Checking repository files.
[1;32m=>[m [xkbcomp] Checking repository files.
[1;32m=>[m [xkeyboard-config] Checking repository files.
[1;32m=>[m [xorg-server] Checking repository files.
[1;32m=>[m [meson] Downloading sources.
[1;32m=>[m [meson] Found cached source '0.51.2.tar.gz'.
[1;32m=>[m [meson] Found local file 'patches/no-gettext.patch'.
[1;32m=>[m [glib] Downloading sources.
[1;32m=>[m [glib] Found cached source 'glib-2.60.6.tar.xz'.
[1;32m=>[m [xorgproto] Downloading sources.
[1;32m=>[m [xorgproto] Found cached source 'xorgproto-2019.1.tar.bz2'.
[1;32m=>[m [libXau] Downloading sources.
[1;32m=>[m [libXau] Found cached source 'libXau-1.0.9.tar.bz2'.
[1;32m=>[m [xcb-proto] Downloading sources.
[1;32m=>[m [xcb-proto] Found cached source 'xcb-proto-1.13.tar.bz2'.
[1;32m=>[m [xorg-util-macros] Downloading sources.
[1;32m=>[m [xorg-util-macros] Found cached source 'util-macros-1.19.2.tar.bz2'.
[1;32m=>[m [libxcb] Downloading sources.
[1;32m=>[m [libxcb] Found cached source 'libxcb-1.13.1.tar.bz2'.
[1;32m=>[m [xtrans] Downloading sources.
[1;32m=>[m [xtrans] Found cached source 'xtrans-1.4.0.tar.bz2'.
[1;32m=>[m [libX11] Downloading sources.
[1;32m=>[m [libX11] Found cached source 'libX11-1.6.8.tar.bz2'.
[1;32m=>[m [libXfixes] Downloading sources.
[1;32m=>[m [libXfixes] Found cached source 'libXfixes-5.0.3.tar.bz2'.
[1;32m=>[m [libXdamage] Downloading sources.
[1;32m=>[m [libXdamage] Found cached source 'libXdamage-1.1.5.tar.bz2'.
[1;32m=>[m [libXext] Downloading sources.
[1;32m=>[m [libXext] Found cached source 'libXext-1.3.4.tar.bz2'.
[1;32m=>[m [libXrender] Downloading sources.
[1;32m=>[m [libXrender] Found cached source 'libXrender-0.9.10.tar.bz2'.
[1;32m=>[m [libXxf86vm] Downloading sources.
[1;32m=>[m [libXxf86vm] Found cached source 'libXxf86vm-1.1.4.tar.bz2'.
[1;32m=>[m [libpciaccess] Downloading sources.
[1;32m=>[m [libpciaccess] Found cached source 'libpciaccess-0.16.tar.bz2'.
[1;32m=>[m [libdrm] Downloading sources.
[1;32m=>[m [libdrm] Found cached source 'libdrm-2.4.99.tar.bz2'.
[1;32m=>[m [libxshmfence] Downloading sources.
[1;32m=>[m [libxshmfence] Found cached source 'libxshmfence-1.3.tar.bz2'.
[1;32m=>[m [libXrandr] Downloading sources.
[1;32m=>[m [libXrandr] Found cached source 'libXrandr-1.5.2.tar.bz2'.
[1;32m=>[m [cmake] Downloading sources.
[1;32m=>[m [cmake] Found cached source 'cmake-3.15.2.tar.gz'.
[1;32m=>[m [llvm] Downloading sources.
[1;32m=>[m [llvm] Found cached source 'llvm-8.0.1.src.tar.xz'.
[1;32m=>[m [python-mako] Downloading sources.
[1;32m=>[m [python-mako] Found cached source 'Mako-1.1.0.tar.gz'.
[1;32m=>[m [mesa] Downloading sources.
[1;32m=>[m [mesa] Found cached source 'mesa-19.1.5.tar.xz'.
[1;32m=>[m [pixman] Downloading sources.
[1;32m=>[m [pixman] Found cached source 'pixman-0.38.4.tar.bz2'.
[1;32m=>[m [freetype-harfbuzz] Downloading sources.
[1;32m=>[m [freetype-harfbuzz] Found cached source 'harfbuzz-2.6.1.tar.xz'.
[1;32m=>[m [freetype-harfbuzz] Found cached source 'freetype-2.10.1.tar.xz'.
[1;32m=>[m [libfontenc] Downloading sources.
[1;32m=>[m [libfontenc] Found cached source 'libfontenc-1.1.4.tar.bz2'.
[1;32m=>[m [libXfont2] Downloading sources.
[1;32m=>[m [libXfont2] Found cached source 'libXfont2-2.0.3.tar.bz2'.
[1;32m=>[m [libepoxy] Downloading sources.
[1;32m=>[m [libepoxy] Found cached source '1.5.3.tar.gz'.
[1;32m=>[m [libxkbfile] Downloading sources.
[1;32m=>[m [libxkbfile] Found cached source 'libxkbfile-1.1.0.tar.bz2'.
[1;32m=>[m [xinit] Downloading sources.
[1;32m=>[m [xinit] Found cached source 'xinit-1.4.1.tar.bz2'.
[1;32m=>[m [xkbcomp] Downloading sources.
[1;32m=>[m [xkbcomp] Found cached source 'xkbcomp-1.4.2.tar.bz2'.
[1;32m=>[m [xkeyboard-config] Downloading sources.
[1;32m=>[m [xkeyboard-config] Found cached source 'xkeyboard-config-2.27.tar.bz2'.
[1;32m=>[m [xorg-server] Downloading sources.
[1;32m=>[m [xorg-server] Found cached source 'xorg-server-1.20.5.tar.bz2'.
[1;32m=>[m [meson] Extracting sources.
creating docs/markdown/snippets/nogettext.md
patching file mesonbuild/modules/i18n.py
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
[1;31m!>[m [meson] Build failed.
```

**Comment by dylanaraps** [comment] 2019-08-31 14:41
Rebuild `python` with `kiss build python` and `kiss install python` and let me know if the issue still occurs.

**Comment by alaughlin** [comment] 2019-08-31 15:33
Yeah that appears to have done the trick. Thanks!

**Closed** 2019-08-31 15:40 UTC
Labels: bug
