### ISSUE TITLE
Update error message

### ISSUE THREAD

**Issue by vaskark** [kisslinux/repo#351] opened 2021-10-06 16:24 UTC
I've gotten this message in the last few days when I run `kiss u`:

```
Signature verification enabled.
fatal: Commit 27980cfa does not have a GPG signature.
```
Any help would be appreciated.
Thanks.

**Comment by dylanaraps** [comment] 2021-10-08 03:23
> Do I have to activate gpg2 using the alternate system?
> 
> Edit: `kiss a` reports ...
> 
> ```
> gnupg2 /usr/bin/gpg
> gnupg2 /usr/bin/gpgsplit
> gnupg2 /usr/bin/gpgv
> ```
> 
> Running `kiss u` again produces the error above.

Yes. Run `kiss a | grep gnupg2 | kiss a -` to swap to gpg2. The same can be done to swap to gnupg1 (modify the command).

**Comment by vaskark** [comment] 2021-10-08 13:46
Nope.  Same error as before.

**Comment by dylanaraps** [comment] 2021-10-08 14:41
Send a full verbose log from the package manager showing the failure. Look at the issue template in https://github.com/kisslinux/kiss for how to get one.

**Comment by vaskark** [comment] 2021-10-09 19:04
When I use root to update the error isn't there, only with my user account. I made my user the owner of the repos, though. Should they be owned by root exclusively? I think I was getting other errors at that point.

**Comment by dylanaraps** [comment] 2021-10-11 05:20
Closing this as I cannot reproduce and there is no clear cause. Commits are all signed (which is what is important).

**Closed by dylanaraps** 2021-10-11 05:20 UTC
Labels: bug, can't reproduce
