### ISSUE TITLE
gtk+2 build failure - libX11 not found

### ISSUE THREAD

**Issue by jedahan** [kisslinux/repo#202] opened 2020-07-06 19:05 UTC
Fresh chroot of kiss, installing gtk+2 because its a make-time dependency of firefox. Whats weird is that configure errors out, but kiss outputs 'gtk+2 Installed successfully.

**Comment by dylanaraps** [comment] 2020-07-06 19:26
I cannot reproduce. Steps I took:

1. `KISS_FORCE=1 kiss r libX11` to remove the package. 
2. `kiss b gtk+2`
3. Build fails as expected.

```sh
Package 'x11-xcb', required by 'cairo', not found
Package 'x11', required by 'xrender', not found
Package 'x11', required by 'cairo', not found
Package 'x11', required by 'xext', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BASE_DEPENDENCIES_CFLAGS
and BASE_DEPENDENCIES_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
-> gtk+2 Build failed
-> gtk+2 Log stored to /home/dylan/conf/cache/kiss/logs/gtk+2-2020-07-06-22:24-22007
Terminated
```

Let me see if I can reproduce this in a clean chroot.

**Comment by dylanaraps** [comment] 2020-07-06 20:58
I cannot reproduce this issue in a clean chroot. You'll need to send the build log my way.

**Comment by dylanaraps** [comment] 2020-07-15 07:11
Closing this as I can still not reproduce it and no one else has reported this issue.

**Closed by dylanaraps** 2020-07-15 07:11 UTC
Labels: can't reproduce
