### ISSUE TITLE
Firefox 71 build fails

### ISSUE THREAD

**Issue by ewenomineaim** [kisslinux/repo#127] opened 2019-12-16 14:41 UTC
Me again!  Lol

I’ve attempted building Firefox a handful of times since last you saw me but it always seems to fail at around `27:56` in the compile “TIER”

I’ve used `KISS_DEBUG=1` so I can upload any info you may need should this be a problem on my machine...

**Comment by dylanaraps** [comment] 2019-12-16 15:04
Hello,

Send me the logs. :)

**Comment by ewenomineaim** [comment] 2019-12-16 15:57
Sorry where are those located?  🤓

**Comment by dylanaraps** [comment] 2019-12-16 16:05
Oh. If you haven't made logs yourself they won't exist. Run the build again with `kiss build firefox 2>&1 | tee ~/firefox-log` to save the build output to a file. :+1:

**Comment by ewenomineaim** [comment] 2019-12-16 17:42
Here you go and thanks

https://transfer.sh/2lkre/firefox.log

**Comment by dylanaraps** [comment] 2019-12-16 17:45
Here's the error:

```
37:21.56 error: failed to run custom build command for `style v0.0.1 (/root/.cache/kiss/build-249/firefox/servo/components/style)`
37:21.56 Caused by:
37:21.56   process didn't exit successfully: `/root/.cache/kiss/build-249/firefox/obj-x86_64-pc-linux-musl/release/build/style-42df6ec1e31209a2/build-script-build` (exit code: 101)
37:21.56 --- stdout
37:21.56 cargo:rerun-if-changed=build.rs
37:21.56 cargo:out_dir=/root/.cache/kiss/build-249/firefox/obj-x86_64-pc-linux-musl/x86_64-unknown-linux-musl/release/build/style-e034a881a93a7c51/out
37:21.56 cargo:rerun-if-changed=properties/Mako-0.9.1.zip
37:21.56 cargo:rerun-if-changed=properties/declaration_block.rs
37:21.56 cargo:rerun-if-changed=properties/longhands/position.mako.rs
37:21.56 cargo:rerun-if-changed=properties/longhands/margin.mako.rs
37:21.56 cargo:rerun-if-changed=properties/longhands/outline.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/counters.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/effects.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/table.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/svg.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/background.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/inherited_ui.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/list.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/inherited_text.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/border.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/text.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/inherited_box.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/box.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/ui.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/font.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/inherited_svg.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/column.mako.rs
37:21.57 cargo:rerun-if-changed=properties/longhands/xul.mako.rs
37:21.58 cargo:rerun-if-changed=properties/longhands/inherited_table.mako.rs
37:21.58 cargo:rerun-if-changed=properties/longhands/padding.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/position.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/margin.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/outline.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/svg.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/background.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/list.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/inherited_text.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/border.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/text.mako.rs
37:21.58 cargo:rerun-if-changed=properties/shorthands/box.mako.rs
37:21.59 cargo:rerun-if-changed=properties/shorthands/font.mako.rs
37:21.59 cargo:rerun-if-changed=properties/shorthands/inherited_svg.mako.rs
37:21.59 cargo:rerun-if-changed=properties/shorthands/column.mako.rs
37:21.59 cargo:rerun-if-changed=properties/shorthands/padding.mako.rs
37:21.59 cargo:rerun-if-changed=properties/gecko.mako.rs
37:21.59 cargo:rerun-if-changed=properties/build.py
37:21.59 cargo:rerun-if-changed=properties/properties.mako.rs
37:21.59 cargo:rerun-if-changed=properties/helpers/animated_properties.mako.rs
37:21.59 cargo:rerun-if-changed=properties/data.py
37:21.59 cargo:rerun-if-changed=properties/computed_value_flags.rs
37:21.59 cargo:rerun-if-changed=properties/properties.html.mako
37:21.59 cargo:rerun-if-changed=properties/helpers.mako.rs
37:21.59 cargo:rerun-if-changed=properties/cascade.rs
37:21.59 cargo:rerun-if-changed=properties/counted_unknown_properties.py
37:21.59 cargo:rerun-if-changed=build_gecko.rs
37:21.59 cargo:rerun-if-changed=/root/.cache/kiss/build-249/firefox/obj-x86_64-pc-linux-musl/layout/style/bindgen.toml
37:21.59 cargo:rerun-if-changed=/root/.cache/kiss/build-249/firefox/layout/style/ServoBindings.toml
37:21.59 --- stderr```

**Comment by dylanaraps** [comment] 2019-12-16 17:45
Output of `kiss list`? Also, is your system up to date? How much ram do you have?

**Comment by ewenomineaim** [comment] 2019-12-16 17:50
Kiss update says I’m already up to date.  Here’s my kiss list https://transfer.sh/10ppun/kiss-list

As for ram I have 4 gb and 16 gb of swap.

**Comment by dylanaraps** [comment] 2019-12-16 19:31
I wonder if this is a low ram issue. You could try building Firefox without these two lines:

```
# These are in the file called 'build' located in '/var/db/repo/extra/firefox`.
cores=$(nproc)
printf '%s\n' "mk_add_options MOZ_MAKE_FLAGS=\"-j$cores -l$cores\"" >> mozconfig
```

You could also change `cores=` to `cores=1` and try that.

**Comment by ewenomineaim** [comment] 2019-12-17 01:10
Both ways (`cores=1` and removing the two lines entirely) resulted in slower but ultimately failing builds, but

By looking at the build log specifically this and the following lines:

`37:21.60 /root/.cache/kiss/build-249/firefox/obj-x86_64-pc-linux-musl/dist/include/mozilla/ServoStyleConsts.h:10840:20: error: class member cannot be redeclared`

... I found several redundant declarations of the same class at the bottom of the “ServoStyleConsts.h” file.  After removing the redundancies I am pleased to say I am currently rebuilding and so far so good (it appears I am past the point where it was previously failing). I will post again upon completion with a fail or pass!

**Comment by tristelune1** [comment] 2019-12-17 07:04
I can report the same problem. I'm unable to build firefox and I find the same errors in the log file.

**Comment by dylanaraps** [comment] 2019-12-17 09:33
@ewenomineaim If the build passes we can add a patch to the package. :+1:

Sadly I can't reproduce this on my machine...

**Comment by tristelune1** [comment] 2019-12-17 10:28
I can test the patch when it will be available.

**Comment by ewenomineaim** [comment] 2019-12-17 10:54
I woke up to a successful build 👍🏻

**Comment by dylanaraps** [comment] 2019-12-17 11:10
Ah. The error is from `cbindgen` and the file doesn't exist in the source until partway through the build process... Can you reproduce the issue with `cbindgen` `0.12.0`?

**Comment by dylanaraps** [comment] 2019-12-17 11:11
Found the bug report on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1602358

**Comment by dylanaraps** [comment] 2019-12-17 11:18
https://github.com/kisslinux/repo/commit/4f7862ca716b09df0ff91e7b3f8d19c09fb4db1d

Try the build again, I've added a patch ported from Firefox beta. :+1:

**Comment by tristelune1** [comment] 2019-12-17 20:49
Great, thank you! :+1:  It works perfectly!

**Comment by dylanaraps** [comment] 2019-12-17 21:04
I can close the issue? :)

**Comment by tristelune1** [comment] 2019-12-17 22:27
For me yes, I don't know for **ewenomineaim**.

**Closed** 2019-12-17 23:42 UTC
