### ISSUE TITLE
wayland

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/repo#270] opened 2021-07-08 07:58 UTC
See: #269 

PS For those scared about dbus, polkit, logind or whathaveyou - this is not a pathway towards their existence.

**Comment by onodera-punpun** [comment] 2021-07-08 08:01
This will replace xorg?

**Comment by dylanaraps** [comment] 2021-07-08 08:14
Yeah. This has always been the plan (for some arbitrary time in the future). Once the LTS releases of distributions swap to Wayland, Firefox will also start dropping Xorg. It's an inevitability in other words.

**Comment by konimex** [comment] 2021-07-08 10:52
Regarding this change, does this have the same urgency as #263 (sooner rather than later)? While a lot of "main" distros are putting on the effort and IIRC Firefox had (or still have?) Wayland-only feature for hardware acceleration (not sure about this one), I personally can't see X being fully replaced (i.e. no Xwayland) at least in 2 years time.

**Comment by dylanaraps** [comment] 2021-07-08 11:05
> Wayland-only feature for hardware acceleration

It's *technically* not *wayland only*, VAAPI on X11 just requires wayland be installed. 
I opened an issue about it https://bugzilla.mozilla.org/show_bug.cgi?id=1662496

> Regarding this change, does this have the same urgency as #263 (sooner rather than later)? 

I'd like to see this happen sooner for a few reasons. 

1. I don't use X11 anymore.
2. I want to make breaking changes *before* people change their remotes back en masse. 
3. Static linking is a possibility (have tested everything static minus mesa).
4. It's more in line with the distribution's goals.

**Comment by dilyn-corner** [comment] 2021-07-08 11:12
https://github.com/kisslinux/repo/issues/99 Drew has been vindicated

**Comment by dylanaraps** [comment] 2021-07-08 12:00
Well, at that time there was no browser we could compile without X11 libraries (let alone the other issues). 
Full wayland (without X11) is actually viable now.

**Comment by sdsddsd1** [comment] 2021-07-08 12:27
Do you have ideas/plans to provide a wayland session with legacy support for programs which don't run in a wayland session(sdl1) or _do_ run but depend on mesa with e.g. `libglx`or need libX11 to work? Lots of possibilities here..
It will be interesting how the for now archived community repository is and will be compatible.

**Comment by dylanaraps** [comment] 2021-07-08 12:38
There will be no X11 support whatsoever. This is a full transition. It should be trivial to maintain xorg support *on top* with your own repository. ie, you don't need **all** the X11 libraries and only a few packages need modification.

For example: https://github.com/dylanaraps/wayland-experiment/tree/master/wayland/xorg-libs

This package (or equivalent) + modification to the mesa package should be all you need.

**Comment by dylanaraps** [comment] 2021-07-08 14:02
https://kisslinux.xyz/news/20210708a

**Comment by konimex** [comment] 2021-07-08 14:21
I know this isn't a support thread but since we're switching to Wayland we need to get everything working first.

Can anyone reproduce this? https://termbin.com/iwex

**Comment by dylanaraps** [comment] 2021-07-08 14:23
Yes. This is https://github.com/kisslinux/kiss/commit/c2216a3388624277835e6103dbd8b3a6e0e86ba8

**Comment by cy6x** [comment] 2021-07-08 14:34
Hi. Will there be information about using Wayland for Nvidia graphics cards on Kiss Wiki anytime soon?

**Comment by dylanaraps** [comment] 2021-07-08 14:37
Wayland (specifically wlroots/sway) is compatible with the open source NVIDIA drivers. It is not compatible with the proprietary drivers. KISS does not officially support proprietary software anyway so this is not a concern of mine (*nor do the proprietary drivers work with musl anyway*).

**Comment by onodera-punpun** [comment] 2021-07-08 19:32
Slightly off topic, but what WM will you be using Dylan?

**Comment by AndreiSva** [comment] 2021-07-08 20:08
I think Wayland is still not developed enough to completely replace Xorg on kisslinux. For me at least it has been buggy on Nvidia video cards.

Perhaps maintaining Wayland packages alongside the old Xorg ones for the next few years is the way to go?

**Comment by dilyn-corner** [comment] 2021-07-09 01:19
When was the last time you tried it, @AndreiSva?

**Comment by dylanaraps** [comment] 2021-07-09 04:31
> Slightly off topic, but what WM will you be using Dylan?

I'm using `sway-tiny`. 

Source code: https://github.com/DCVIII/sway/

> Perhaps maintaining Wayland packages alongside the old Xorg ones for the next few years is the way to go?

If I were being paid for support, sure - but I'm not. I'm going to dedicate my time where *I* want it to go.
Of course, nothing prevents *anyone* from taking the `xorg` repository and maintaining it from here on.
(that's the idea).

**Comment by Vouivre** [comment] 2021-07-09 07:18
Could we open an issue/page on the wiki for wayland version of some softwares ? The won't be 1:1 but It would be a good starting point to make the switch. For example I use `sxiv` and don't expect it will work. I know `imv` could replace it. Same for `dmenu` replaced by `bemenu`. But I don't know for `st` and for the notification system `herbe`. 

A quick search will give me an alternative for `st` but it would be interesting to share what we will use. I also expect some suprises.

**Comment by dylanaraps** [comment] 2021-07-09 07:23
> Could we open an issue/page on the wiki for wayland version of some softwares ? The won't be 1:1 but It would be a good starting point to make the switch. For example I use `sxiv` and don't expect it will work. I know `imv` could replace it. Same for `dmenu` replaced by `bemenu`. But I don't know for `st` and for the notification system `herbe`.
> 
> A quick search will give me an alternative for `st` but it would be interesting to share what we will use. I also expect some suprises.
> 
> EDIT: I forgot `sxhkd`which I need. I know there is an alternative which I have to find or I could implement some keybind in `sway` if I use it.

Done: https://github.com/kisslinux/wiki/issues/79

**Comment by dylanaraps** [comment] 2021-07-09 20:00
Found this which may be of interest to people: https://github.com/fluix-dev/sway-borders

**Comment by git-bruh** [comment] 2021-07-11 12:42
Does this unban pipewire from the repositories, since it's required for screen sharing ?

**Comment by dylanaraps** [comment] 2021-07-11 12:47
> Does this unban pipewire from the repositories, since it's required for screen sharing ?

It's still excluded (same as bluez (due to dbus), etc). I'd love to see the community package this and other software.

**Closed** 2021-07-11 15:03 UTC
Labels: note
