### ISSUE TITLE
nodejs: fails to build

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/repo#167] opened 2020-03-10 02:53 UTC
NOTE: ignore the "which" command not found messages, as it is just searching for "which" in order to find a python version, but still ends up finding python in the end, I'm fairly sure that is not the cause of the failure.

`kiss b nodejs`

```
./configure: 3: ./configure: which: not found
./configure: 4: ./configure: which: not found
./configure: 5: ./configure: which: not found
./configure: 6: ./configure: which: not found
./configure: 7: ./configure: which: not found
Node.js configure: Found Python 3.8.2...
INFO: configure completed successfully
ninja: invalid pool depth '1.4507365226745605'
```

**Comment by a-schaefers** [comment] 2020-03-10 03:17
I'm trying to build it using make at the moment. Seems to be building...

Konimex has reported in IRC that also starts to build using ninja.

So it might be a samurai bug.

**Comment by konimex** [comment] 2020-03-10 03:19
> Konimex has reported in IRC that also starts to build using ninja.

Not me, that one's E5ten. I'm just reverting to the old GNU make at the moment.

**Comment by a-schaefers** [comment] 2020-03-10 03:44
I dropped the samurai dependency and built it like this without issue:

```bash
#!/bin/sh -e

python ./configure.py \
       --shared-zlib \
       --without-intl \
       --without-etw \
       --without-dtrace \
       --without-report \
       --without-node-snapshot \
       --without-node-code-cache

make
make DESTDIR="$1" install

# Remove unneeded headers.
rm -rf "$1/usr/include/node/openssl"
```

**Comment by michaelforney** [comment] 2020-03-10 04:19
Looks like this is a python2 vs python3 compatibility issue that went unnoticed since ninja accepts any garbage after the initial integer part of the depth string, so it was accidentally doing the right thing.

Only integer pool sizes make sense (it is the maximum number of jobs that can run at the same time, and you can't run part of a job). gyp calculates the size of the pool based on the amount of memory you have:

https://github.com/nodejs/node/blob/73f2dbc911e16a3b50fc9a1236d9bed7d9e04d7a/tools/gyp/pylib/gyp/generator/ninja.py#L1789

In python2, the result of the `/` operator on integers is an integer, but in python3, it is a float, which is causing

```
pool link_pool
  depth = 1.4507365226745605
```

in the output.

This was fixed in upstream gyp in https://chromium.googlesource.com/external/gyp/+/ab4aca868d68b9de9b20a9991bbbb5e78ab48a30%5E%21/#F22, but it looks like this change is missing in https://github.com/nodejs/node-gyp, which is where the vendored gyp in nodejs comes from.

To work around this, I recommend applying the following diff, and opening an issue at https://github.com/nodejs/node-gyp.

```diff
diff --git a/tools/gyp/pylib/gyp/generator/ninja.py b/tools/gyp/pylib/gyp/generator/ninja.py
index d5006bf84a..33e1c98b2a 100644
--- a/tools/gyp/pylib/gyp/generator/ninja.py
+++ b/tools/gyp/pylib/gyp/generator/ninja.py
@@ -1786,7 +1786,7 @@ def GetDefaultConcurrentLinks():
           if not match:
             continue
           # Allow 8Gb per link on Linux because Gold is quite memory hungry
-          return max(1, int(match.group(1)) / (8 * (2 ** 20)))
+          return max(1, int(match.group(1)) // (8 * (2 ** 20)))
     return 1
   elif sys.platform == 'darwin':
     try:
```

**Comment by dylanaraps** [comment] 2020-03-10 07:38
Fixed. What's odd is that I cannot reproduce this on my machine (no python2 installed).

@michaelforney thanks for tracking down the exact issue.

**Closed** 2020-03-10 07:38 UTC

**Comment by dylanaraps** [comment] 2020-03-10 07:42
Opened an issue here: https://github.com/nodejs/node-gyp/issues/2065

**Comment by dylanaraps** [comment] 2020-03-10 07:45
NOTE: The reason I swapped to using samurai for the build is that it's a lot faster. It also works with `ccache` a lot better. Rebuilds take 30 seconds for the same sources and full builds on updates will take less time.
