### ISSUE TITLE
unable to install linux 5.15.58

### ISSUE THREAD

**Issue by imxade** [kisslinux/repo#391] opened 2022-08-02 14:17 UTC
```sh
BusyBox v1.34.1 (2022-07-30 16:03:45 UTC) multi-call binary.

Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2

Compare files line by line and output the differences between them.
This implementation supports unified diffs only.

	-a	Treat all files as text
	-b	Ignore changes in the amount of whitespace
	-B	Ignore changes whose lines are all blank
	-d	Try hard to find a smaller set of changes
	-i	Ignore case differences
	-L	Use LABEL instead of the filename in the unified header
	-N	Treat absent files as empty
	-q	Output only whether files differ
	-r	Recurse
	-S	Start with FILE when comparing directories
	-T	Make tabs line up by prefixing a tab when necessary
	-s	Report when two files are the same
	-t	Expand tabs to spaces in output
	-U	Output LINES lines of context
	-w	Ignore all whitespace
Warning: Kernel ABI header at 'tools/arch/x86/include/asm/inat.h' differs from latest version at 'arch/x86/include/asm/inat.h'
diff: unrecognized option: I
BusyBox v1.34.1 (2022-07-30 16:03:45 UTC) multi-call binary.

Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2

Compare files line by line and output the differences between them.
This implementation supports unified diffs only.

	-a	Treat all files as text
	-b	Ignore changes in the amount of whitespace
	-B	Ignore changes whose lines are all blank
	-d	Try hard to find a smaller set of changes
	-i	Ignore case differences
	-L	Use LABEL instead of the filename in the unified header
	-N	Treat absent files as empty
	-q	Output only whether files differ
	-r	Recurse
	-S	Start with FILE when comparing directories
	-T	Make tabs line up by prefixing a tab when necessary
	-s	Report when two files are the same
	-t	Expand tabs to spaces in output
	-U	Output LINES lines of context
	-w	Ignore all whitespace
Warning: Kernel ABI header at 'tools/arch/x86/include/asm/insn.h' differs from latest version at 'arch/x86/include/asm/insn.h'
diff: unrecognized option: I
BusyBox v1.34.1 (2022-07-30 16:03:45 UTC) multi-call binary.

Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2

Compare files line by line and output the differences between them.
This implementation supports unified diffs only.

	-a	Treat all files as text
	-b	Ignore changes in the amount of whitespace
	-B	Ignore changes whose lines are all blank
	-d	Try hard to find a smaller set of changes
	-i	Ignore case differences
	-L	Use LABEL instead of the filename in the unified header
	-N	Treat absent files as empty
	-q	Output only whether files differ
	-r	Recurse
	-S	Start with FILE when comparing directories
	-T	Make tabs line up by prefixing a tab when necessary
	-s	Report when two files are the same
	-t	Expand tabs to spaces in output
	-U	Output LINES lines of context
	-w	Ignore all whitespace
Warning: Kernel ABI header at 'tools/arch/x86/lib/inat.c' differs from latest version at 'arch/x86/lib/inat.c'
diff: unrecognized option: I
BusyBox v1.34.1 (2022-07-30 16:03:45 UTC) multi-call binary.

Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2

Compare files line by line and output the differences between them.
This implementation supports unified diffs only.

	-a	Treat all files as text
	-b	Ignore changes in the amount of whitespace
	-B	Ignore changes whose lines are all blank
	-d	Try hard to find a smaller set of changes
	-i	Ignore case differences
	-L	Use LABEL instead of the filename in the unified header
	-N	Treat absent files as empty
	-q	Output only whether files differ
	-r	Recurse
	-S	Start with FILE when comparing directories
	-T	Make tabs line up by prefixing a tab when necessary
	-s	Report when two files are the same
	-t	Expand tabs to spaces in output
	-U	Output LINES lines of context
	-w	Ignore all whitespace
Warning: Kernel ABI header at 'tools/arch/x86/lib/insn.c' differs from latest version at 'arch/x86/lib/insn.c'
In file included from /usr/include/linux/byteorder/little_endian.h:13,
                 from /usr/include/asm/byteorder.h:5,
                 from /usr/src/linux-5.15.58/tools/arch/x86/include/asm/insn.h:10,
                 from arch/x86/decode.c:10:
/usr/include/linux/swab.h:136:23: error: expected ';' before 'unsigned'
  136 | static __always_inline unsigned long __swab(const unsigned long y)
      |                       ^~~~~~~~~
      |                       ;
/usr/include/linux/swab.h:171:8: error: unknown type name '__always_inline'
  171 | static __always_inline __u16 __swab16p(const __u16 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/swab.h:171:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__swab16p'
  171 | static __always_inline __u16 __swab16p(const __u16 *p)
      |                              ^~~~~~~~~
/usr/include/linux/swab.h:184:8: error: unknown type name '__always_inline'
  184 | static __always_inline __u32 __swab32p(const __u32 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/swab.h:184:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__swab32p'
  184 | static __always_inline __u32 __swab32p(const __u32 *p)
      |                              ^~~~~~~~~
/usr/include/linux/swab.h:197:8: error: unknown type name '__always_inline'
  197 | static __always_inline __u64 __swab64p(const __u64 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/swab.h:197:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__swab64p'
  197 | static __always_inline __u64 __swab64p(const __u64 *p)
      |                              ^~~~~~~~~
/usr/include/linux/swab.h:252:23: error: expected ';' before 'void'
  252 | static __always_inline void __swab32s(__u32 *p)
      |                       ^~~~~
      |                       ;
/usr/include/linux/swab.h:265:23: error: expected ';' before 'void'
  265 | static __always_inline void __swab64s(__u64 *p)
      |                       ^~~~~
      |                       ;
In file included from /usr/include/asm/byteorder.h:5,
                 from /usr/src/linux-5.15.58/tools/arch/x86/include/asm/insn.h:10,
                 from arch/x86/decode.c:10:
/usr/include/linux/byteorder/little_endian.h:44:8: error: unknown type name '__always_inline'
   44 | static __always_inline __le64 __cpu_to_le64p(const __u64 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:44:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__cpu_to_le64p'
   44 | static __always_inline __le64 __cpu_to_le64p(const __u64 *p)
      |                               ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:48:8: error: unknown type name '__always_inline'
   48 | static __always_inline __u64 __le64_to_cpup(const __le64 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:48:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__le64_to_cpup'
   48 | static __always_inline __u64 __le64_to_cpup(const __le64 *p)
      |                              ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:52:8: error: unknown type name '__always_inline'
   52 | static __always_inline __le32 __cpu_to_le32p(const __u32 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:52:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__cpu_to_le32p'
   52 | static __always_inline __le32 __cpu_to_le32p(const __u32 *p)
      |                               ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:56:8: error: unknown type name '__always_inline'
   56 | static __always_inline __u32 __le32_to_cpup(const __le32 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:56:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__le32_to_cpup'
   56 | static __always_inline __u32 __le32_to_cpup(const __le32 *p)
      |                              ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:60:8: error: unknown type name '__always_inline'
   60 | static __always_inline __le16 __cpu_to_le16p(const __u16 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:60:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__cpu_to_le16p'
   60 | static __always_inline __le16 __cpu_to_le16p(const __u16 *p)
      |                               ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:64:8: error: unknown type name '__always_inline'
   64 | static __always_inline __u16 __le16_to_cpup(const __le16 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:64:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__le16_to_cpup'
   64 | static __always_inline __u16 __le16_to_cpup(const __le16 *p)
      |                              ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:68:8: error: unknown type name '__always_inline'
   68 | static __always_inline __be64 __cpu_to_be64p(const __u64 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:68:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__cpu_to_be64p'
   68 | static __always_inline __be64 __cpu_to_be64p(const __u64 *p)
      |                               ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:72:8: error: unknown type name '__always_inline'
   72 | static __always_inline __u64 __be64_to_cpup(const __be64 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:72:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__be64_to_cpup'
   72 | static __always_inline __u64 __be64_to_cpup(const __be64 *p)
      |                              ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:76:8: error: unknown type name '__always_inline'
   76 | static __always_inline __be32 __cpu_to_be32p(const __u32 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:76:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__cpu_to_be32p'
   76 | static __always_inline __be32 __cpu_to_be32p(const __u32 *p)
      |                               ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:80:8: error: unknown type name '__always_inline'
   80 | static __always_inline __u32 __be32_to_cpup(const __be32 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:80:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__be32_to_cpup'
   80 | static __always_inline __u32 __be32_to_cpup(const __be32 *p)
      |                              ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:84:8: error: unknown type name '__always_inline'
   84 | static __always_inline __be16 __cpu_to_be16p(const __u16 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:84:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__cpu_to_be16p'
   84 | static __always_inline __be16 __cpu_to_be16p(const __u16 *p)
      |                               ^~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:88:8: error: unknown type name '__always_inline'
   88 | static __always_inline __u16 __be16_to_cpup(const __be16 *p)
      |        ^~~~~~~~~~~~~~~
/usr/include/linux/byteorder/little_endian.h:88:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__be16_to_cpup'
   88 | static __always_inline __u16 __be16_to_cpup(const __be16 *p)
      |                              ^~~~~~~~~~~~~~
make[4]: *** [/usr/src/linux-5.15.58/tools/build/Makefile.build:97: /usr/src/linux-5.15.58/tools/objtool/arch/x86/decode.o] Error 1
make[3]: *** [/usr/src/linux-5.15.58/tools/build/Makefile.build:139: arch/x86] Error 2
make[2]: *** [Makefile:56: /usr/src/linux-5.15.58/tools/objtool/objtool-in.o] Error 2
make[1]: *** [Makefile:69: objtool] Error 2
make: *** [Makefile:1396: tools/objtool] Error 2
```

**Comment by aabacchus** [comment] 2022-08-03 17:37
https://kisslinux.org/install.html#024

**Comment by imxade** [comment] 2022-08-04 20:37
> https://kisslinux.org/install.html#024

thanks

**Comment by aabacchus** [comment] 2022-08-04 23:37
Are you sure you did `sed -i '/<stdlib.h>/a #include <linux/stddef.h>' tools/objtool/arch/x86/decode.c`? I can reproduce your error but it is fixed by adding the #include.

**Comment by imxade** [comment] 2022-08-05 08:12
> Are you sure you did `sed -i '/<stdlib.h>/a #include <linux/stddef.h>' tools/objtool/arch/x86/decode.c`? I can reproduce your error but it is fixed by adding the #include.

i added '#include <linux/stddef.h>' above stdlib.h.
will try adding it below that

**Comment by imxade** [comment] 2022-08-05 10:06
> Are you sure you did `sed -i '/<stdlib.h>/a #include <linux/stddef.h>' tools/objtool/arch/x86/decode.c`? I can reproduce your error but it is fixed by adding the #include.

no that's not working for me

**Comment by aabacchus** [comment] 2022-08-05 11:05
I can't reproduce this. Maybe your .config is building more tests? For `defconfig`, arch/x86/tools/insn_decoder_test.c isn't compiled for me. You could try adding the `#include <linux/stddef.h>` to those files?

**Closed** 2022-08-06 08:08 UTC
