### ISSUE TITLE
firefox seems to need libepoxy as a dependency, it should be added to the depends file

### ISSUE THREAD

**Issue by AndreiSva** [kisslinux/repo#285] opened 2021-07-15 02:35 UTC
I've noticed today that firefox refuses to build without libpoxy but does not pull it in as a dependency. This should be fixed.

**Comment by dylanaraps** [comment] 2021-07-15 03:52
Well, libepoxy is a dependency of gtk+3 which is a dependency of Firefox. Firefox itself has no dependency on libepoxy (https://searchfox.org/mozilla-central/search?q=epoxy&path=&case=false&regexp=false). Closing this as I can't see what the issue is. Next time send logs.

**Closed by dylanaraps** 2021-07-15 03:52 UTC
