### ISSUE TITLE
why ?

### ISSUE THREAD

**Issue by deepnum** [kisslinux/repo#118] opened 2019-11-09 19:14 UTC
>Explicitly excludes the following software: dbus, systemd, polkit, gettext, intltool, pulseaudio, pam, wayland, logind, ConsoleKit2 and all Desktop Environments.

why walyland is on this list?

**Comment by dylanaraps** [comment] 2019-11-09 19:34
Duplicate of https://github.com/kisslinux/repo/issues/99

**Closed by dylanaraps** 2019-11-09 19:34 UTC
